/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./src/models/cube.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cube.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['red material']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['texture material']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['emissive material']} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['emissive texture']} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/cube.glb')
