//@ts-ignore
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 simple_concert_stage.glb 
Author: mertart3D (https://sketchfab.com/mertbbicak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-concert-stage-d5c7733d06d24947bf60b3a0fe203f69
Title: Simple Concert Stage
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Concert_hall(props) {
  const { nodes, materials } = useGLTF("/simple_concert_stage.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["concert-stagemainfinal__0"].geometry}
        material={materials["Scene_-_Root"]}
        position={[0, -6.206, -858.955]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/simple_concert_stage.glb");
